# DentalSync - Docker Compose Minimalista
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=dentalsync
      - DB_USERNAME=dentalsync
      - DB_PASSWORD=password

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dentalsync
      MYSQL_USER: dentalsync
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
